# Generated by Django 4.1.7 on 2023-05-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_context_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.answer')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.context')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.question')),
            ],
            options={
                'unique_together': {('participant', 'context', 'question')},
            },
        ),
    ]
