# Generated by Django 4.1.7 on 2023-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_question_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(),
        ),
    ]
