# Generated by Django 4.1.7 on 2023-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_participantsubmission_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='expo_token',
            field=models.TextField(null=True),
        ),
    ]
