# Generated by Django 4.1.7 on 2023-06-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_participant_expo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ping_times',
            field=models.TextField(),
        ),
    ]
