# Generated by Django 4.1.7 on 2023-07-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_schedule_ping_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_female',
            field=models.BooleanField(default=True),
        ),
    ]
